### ISSUE TITLE
对象适配器模式中的问题

### ISSUE THREAD

**Issue by youlanstudio** [InnoFang/DesignPatterns#1]
对象适配器模式中，Adapter.java里面，operation()方法中，应该还需要调用adaptee 的adaptedOperation方法才正确。类适配模式中有类似的问题。

**Comment by InnoFang** [comment]
嗯，我觉得你说的不全对，还是得根据具体情况来定。
&nbsp;
**Adapter 的存在是为了解决 Adaptee 对目标类的不兼容**。如果只是简单的调用 adaptee 的方法，那么并不能达到适配的目的。但是如果需要借助 Adaptee 的结果来达到适配的目的，那么调用 Adaptee 的方法是应该的。因为我的例子写的很简单，仅仅只是输出一条语句，而且我的 base 包下的代码是为了生成 uml 类图用的，所以没有考虑复杂的情况。
&nbsp;
不知道我讲明白了吗？如果说错了，欢迎指正 :-)
